<?php
// $Id$

/**
 * @file
 * This integrates the drupal APC cache module.
 */

function apc_permission() {
  return array(
    'access apc statistics' =>  array(
      'title' => t('Access apc statistics'),
      'description' => t('Allows access to the statistics reports of APC.'),
    ),
  );
}

function apc_requirements($phase) {
  $requirements = array();
  // Ensure translations don't break at install time
  $t = get_t();

  // Test APC.
  $apc_version = phpversion('apc');
  $requirements['apc'] = array(
    'title' => $t('APC'),
    'value' => empty($apc_version) ? $t('Not available') : $apc_version,
    'description' => $t('The APC module needs the apc extension see: http://www.php.net/apc.'),
    'severity' => empty($apc_version) ? REQUIREMENT_ERROR : REQUIREMENT_OK,
  );

  return $requirements;
}
